### ISSUE TITLE
va-card__inner don't have height 100%

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#1354]
**Vuestic-ui version:** 1.3.3

Setting 

```css
.va-card {
  height: 100%;
}
```

don't work
