### ISSUE TITLE
Check that overrides.css works correctly

### ISSUE THREAD

**Issue by Derranion** [epicmaxco/vuestic-ui#1357]
**Vuestic-ui version:** 1.3.3

**What is the expected behavior?**
`overrides.css` file should correctly override styles.
Here is our [documentation link](https://vuestic.dev/en/styles/css-variables#overriding) with an example.

**What is the current behavior?**
According to this [feedback from our discord](https://discord.com/channels/457593300799717377/771405067474567178/923297276791783446).
`overrides.css` works correctly only locally (`yarn serve`) but gets overwritten by other styles once project is getting build.
To test this you can use already existed script `yarn serve:production` or `npm run serve:production`

You can find more related info under [this discord comment](https://discord.com/channels/457593300799717377/771405067474567178/923297276791783446).

**To do list:**
- [ ] Find out what can cause such a behavior
- [ ] Fix it or add an additional info to our docs describing how to manage such cases

**Comment by Shiinoya** [comment]
I have found a work-around for the issue thanks to @ankitsinghaniyaz (https://github.com/vuejs/vue-loader/issues/808#issuecomment-355769280)

Changing `:root` to `#app` solves the issue when running `serve` and/or `serve:production`.

```
:root {
  --va-alert-align-items: left;

  --va-card-border-radius: 1.5rem;
```
changed to:
```
#app {
  --va-alert-align-items: left;

  --va-card-border-radius: 1.5rem;
```

**Comment by m0ksem** [comment]
I can propose to change the approach of CSS variables. In VaTimePicker I tested if we can move CSS variables from :root, to component class. [Colors demo](https://vuestic.dev/en/ui-elements/date-picker#colors)

```scss
.va-date-picker {
  --va-date-picker-color: var(--va-primary);
}
```

This allows us to change CSS variable for one specific component in component. 
For example, we have `color` CSS variable that used inside VaDatePicker, and it's nested components. Changing CSS variable declared inside component class automatically change it inside child HTML elements, and VaDatePickerCell will have the same color declared in VaDatePicker. For that, we can bind props to component's style. For some reason, if we declare CSS variable in :root or #app this feature will not work.


User also still able to change CSS variable globally.
```scss
.va-date-picker {
  --va-date-picker-color: #ff00ff !important;
}
```
or locally
```scss
.my-cool-component .va-date-picker {
  --va-date-picker-color: #ff00ff !important;
}
// or with Vue scoped
.va-date-picker[data-v-4erfgth] {
  --va-date-picker-color: #ff00ff !important;
}
```


### Issues
The problem here: user should use `!important`, because CSS variables declared as style on component root DOM element.
This issue can not be solved using [SFC `v-bind` in CSS](https://v3.vuejs.org/api/sfc-style.html#state-driven-dynamic-css), because it would be easy to break if user want to redefine some variable globally. 

Do you have any ideas? I still don't know how it impacts performance.
