### ISSUE TITLE
Investigate local reset for components

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#1824]
In ant-design-vue they include the following reset mixin for each component.

Curious if it would be beneficial for us to do something similar.

```less
.reset-component() {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
  color: @text-color;
  font-size: @font-size-base;
  font-variant: @font-variant-base;
  line-height: @line-height-base;
  list-style: none;
  font-feature-settings: @font-feature-settings-base;
}
```
