### ISSUE TITLE
Typography missing font-family

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#2131]
![image](https://user-images.githubusercontent.com/23530004/180430663-27d5c3d4-0b16-41a4-aa47-53df009fccf6.png)

For now, user need to wrap with `.va-content` so typography will work. Need to add font-family everywhere in typography module. For example, simply add 
```css
body, * { font-familty: var(--va-font-family); }
```
