### ISSUE TITLE
Data table inputs looks bad

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#2324]
Inputs must be 100%
https://vuestic.dev/en/ui-elements/data-table#other

Also you might change input min width to fit small cells:
Same for select
```scss
    .va-input, .va-select {
        --va-form-element-default-width: 80px;
        width: 100%;
    }
```
