### ISSUE TITLE
Secondary CSS variables

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#2361]
See https://github.com/epicmaxco/vuestic-ui/issues/2359

We can make something like this:

```scss
--va-select-icon-size: unset;

// ...

.icon {
   font-size: var(--va-select-icon-size, v-bind(sizesConfig.fontSize))
}
```
This way, browser will fall back to sizesConfig, but user are able to change size via CSS variables.
