### ISSUE TITLE
Unclear style import order with esm build

### ISSUE THREAD

**Issue by Valar103769** [epicmaxco/vuestic-ui#2556]
// main.js
```js
import 'vuestic-ui/styles/essential.css'
import '@/assets/tailwind.css'
```
// @/assets/tailwind.css
```css
@import url('https://fonts.googleapis.com/css2?family=Source+Sans+Pro:ital,wght@0,400;1,700&display=swap');
@import url('https://fonts.googleapis.com/icon?family=Material+Icons');
@tailwind base;
@tailwind components;

.va-dropdown__content {
  padding: 0 !important;
}

@tailwind utilities;

```

<img width="1495" alt="image" src="https://user-images.githubusercontent.com/36926073/197098521-78e1aca5-8935-4a67-91a7-6ea3d63549cf.png">

 `mr-3` is under `vuestic-ui/styles/essential.css`, the expected situation is that mr-3 takes effect

how to resolve it please?
