### ISSUE TITLE
Make config to understand color names in kebab case

### ISSUE THREAD

**Issue by aluarius** [epicmaxco/vuestic-ui#2753]
Now we are able to use only camel case names in colors config:

```CSS
{
  primary: "#4d4d4d",
  anotherColor: "#fafafa",

  // not this
  'some-name': '#000000',
}
```

But it's inconviently, especially for https://github.com/epicmaxco/vuestic-ui/pull/2745
