### ISSUE TITLE
unable to override global vars in Nuxt

### ISSUE THREAD

**Issue by tasiotas** [epicmaxco/vuestic-ui#2917]
hi,

I would like to override globally few variables.

1. create file with overrides

va-overrides.scss
```css
:root {
  --va-checkbox-square-border-radius: 50%;
  --va-input-border-radius: 99999px;
}
```

2. load it in nuxt.config.ts
```ts
  'css': [
    '~/assets/css/main.scss',
    '~/assets/css/va-overrides.scss',
  ],
```

3. override is loaded before vuestic files, so va-override gets overridden :)
![image](https://user-images.githubusercontent.com/9046931/216719406-968993eb-1eeb-4e42-8187-d09c08c57dfb.png)

Is there other way of loading such overrides, or could you provide it via `vuestic` config.
For example:
```ts
  'vuestic': {
    config: {
      colors: {
        currentPresetName: 'light',
      },
    },
    css: ['typography', 'reset'],
    fonts: false,
    overrides: ['~/assets/css/va-overrides.scss'], // <- just an idea
  },

```
