### ISSUE TITLE
pseudo element at striped/hoverable state of `DataTable`

### ISSUE THREAD

**Issue by demershov** [epicmaxco/vuestic-ui#3613]
If `striped` or `hoverable` props are set for `DateTable`, then a pseudo element is added for the table rows. This pseudo element breaks the behavior if a border is set for a table cell, because the pseudo element is superimposed on top.

https://codesandbox.io/p/sandbox/xenodochial-voice-hm6swz

I think that the pseudo element approach is not suitable, why can't we just change the background color, for example?

**Comment by m0ksem** [comment]
We usually use pseudo-elements to add opacity to the color without using JS.

```css
:before {
   background: var(--va-primary);
   opacity: 0.5;
}
```

We could use here `useColors` and translate color in JS. I assume there are no difference in performance between these two approaches.

**Comment by demershov** [comment]
@m0ksem Thanks for the quick response.

Unfortunately, I didn't quite understand your message. The `after` pseudo element is used for table rows. Could you write in more detail what you meant.

Thanks.

**Comment by m0ksem** [comment]
> why can't we just change the background color

Answering your question, why we can not just change background-color. 

The idea of having `after` pseudo-element in having the ability to set an opacity for background color. If we have a color in props like `#f0ff0f` how do we apply opacity 0.2? The following code snippet solves it:

```css
:after {
   background: #f0ff0f;
   opacity: 0.2;
}
```

This approach is useful because you can change color with CSS variables and don't think about opacity. For example, if you're using css variables like `var(--va-primary)`, `var(--va-danger)`. Downside of this approach is if you set color to `rgba(255, 0,0, 0.5)` additional 0.2 opacity will be applied. In future I'd like have an interface like `rgba(var(--va-primary-raw, 0.5)` where `--va-primary-raw` is equal to `255, 0, 0` instead of `rgba(255, 0, 0, 1)`. 


For now, you can manually restyle component and remove `:after` and set the background color to `td`. Something like this must work:

```css
.va-data-table {
   tr { display: none; }
   
   tr:hover td {
      background: var(--va-data-table-hover-color);
   }
}
```
