### ISSUE TITLE
<VaInput> label font size

### ISSUE THREAD

**Issue by All-The-Best-for** [epicmaxco/vuestic-ui#4179]
**Hello**

**May I ask how to modify the font size of the label on the<VaInput> 's label**
![Snipaste_2024-03-11_16-22-34](https://github.com/epicmaxco/vuestic-ui/assets/76414672/68cf212d-3455-493b-9672-07da4ad7aecd)

**Thanks！**

**Comment by m0ksem** [comment]
You can manually update css.

```css
.va-input-wrapper  .va-input-label {
   font-size: 0.9rem;
}

```
